name: GitHub Tests
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo " The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          cd ${{ github.workspace }}
          cp bluej/build.properties.template bluej/build.properties
          sed -i 's/build_java_home=.*/build_java_home=\/usr\/lib\/jvm\/temurin-17-jdk-amd64\//' bluej/build.properties
          sed -i 's/openjfx_path.*/openjfx_path=\/usr\/share\/openjfx_monocle-sdk-gluon-17.0.3\//' bluej/build.properties
          sed -i 's/openjfx_monocle_path.*/openjfx_monocle_path=\/usr\/share\/openjfx_monocle-sdk-gluon-17.0.3\//' bluej/build.properties
          JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64 cd bluej && ant clean && ant update-version-number && ant ready-to-run && xvfb-run ant test && cd ../greenfoot && ant clean && ant update-version-number && ant ready-to-run && xvfb-run ant test && cd .. && bash check-copyright.sh
      - run: echo "This job's status is ${{ job.status }}."

